services:
  db:
    image: mysql:8.0
    container_name: Mantencion_Fishcare_db
    environment:
      MYSQL_ROOT_PASSWORD: fishybusiness
      MYSQL_DATABASE: mantencion
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5
    restart: always

  app:
    build: .
    container_name: Mantencion_Fishcare_app
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      DB_HOST: db
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    restart: always

volumes:
  mysql_data: